version: 1.0.0
variables:
  global:
    N3_KEY: 'c694314e-e9ee-413e-b999-9dcd3caf6d0d'
    N3_SECRET:
      secure: 2acjm4oCVJebCy3oV7sjoOESrrsmnrCw5eDUNcGFFA+nqbAWGppSSIdA3/+YJ0zpxT4/UMO92/aGd5PxLSrfypVjHRwxwRXQVkiDA++DMYgDX5yoKQkUjcduynyABwdEHMEQHizp/OZZ7kfSeBjY3TgKJHiIOM/nhL+sIKM0Bz3YCJ1FxPlumjwvAxupMyChKs3tVehbv0Wnz6l89C7RUCq9VydVjEt0hCUWWSoPE6I0RXcRUrgP3o3iTDxAu9Aec6I89K+QytLldl06zZgHYXeQdjXv19U3SAHP6B0qngHqcqHy43t8i/POz73Kwe62xRq19CuQ/sYGPfl+nZ7Nlc1caezxSWlAuwvLYeX8n++JC6RBlv2mzDRR36iYJvBWXOR560+bZy7tIHRzWOceO4r3TvsyOKM6WXqqZHwutg29dWV8NrAM1T397PHXf3C35BfZ4tA4ivJugKtZHisW/5mu92FGnJX4YtklJA4xgtiZkt8A2XCVQsTvFv3JokfgE0ffiKXmVI5aREJWnEe54aX2pvP2bgNbK5+kAYje2KLtJ9lcPSnD32KlxwuLGowZ/5gxgAnHb4dm3dO1FmcT7PQ9T5b42aEoy03Z19On32yp5tVbeXHbYpzZn+8Fvka3BaRL2WVTSmAuhky5KYlfioPAmDV2+mAAO6zzK8viV1Sauo=D08EcwmIIAEE5X78ThoKoKlxUwEPB/hSf/kJB5dLKXE2vp5O6xN+tsYFDtQFMiD4bhcBRbnjGmI4GyoD6dTK+/nBU5nnsRcz2NszK+M3zzI43TXfqK44Laqi8coUFoWW
services:
  - mysql
events:
  build:
    steps:
      -
        composer:
          type: script
          script:
            - 'composer install -vvv &'
            - 'mysql -u root -proot -e "CREATE DATABASE drupal"'
            - 'cd docroot'
            - '/usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ../vendor/bin/drush site-install -y --db-url=mysql://root:root@127.0.0.1:3306/drupal'
            - 'php -S 127.0.0.1:8081 &'
            - 'sleep 2'
            - 'cd ..'
            - ./vendor/bin/behat
