version: 1.0.0
variables:
  global:
    N3_SECRET:
      secure: 2achW1Q1CVGu2atrj+8S5PqZkeFeU/333hhnxFgIOY9rwNtSv/oSaG5+J1FJXJs9rw/Q2fpEjUQpwemGjTaPk+JTC4be/EIOa9hMPEKy68t/apoXk98s1yZwikmbCdxHS3ZOBMPk6ACN1nMYdqjaaB4QesOZ86DJD4qQQ3MXSUNqXcljsy9+qN8R7NMroiffnyx008fsC1L9D1DXwsaODFkIJGo94CwkbarcK33ShUWBqb0vmmS3D1o42rrCIDEF3Vvp50GT5RT9f+lyAfEJljRC0vCkqxq1VDwZXvVLIr+Thry52nZMIG+aLBTTN8xCPDk5ATGaBV3mLqECHomyzjZJ5UdjV71Ls7DCG2Bcb+o8qTJDD5Je6yS98rYhW/LIeN7JsoXxXbQ+/mLkZO52iiDV6nStYU4hLL5yMOg6kPuhnNCc1JPUB8lcMRciDDSASlvhYwq6xdzea7ct4BtDKEgJM6u9iU7SsqOkZvVppt5IQ2olO/EnOhbxBnD49tu6jVOgiqL9sTOgFd87VayH1EMqOvLGBekHYkMuSGMSG+uTt+9OnYfNCIrTua3+Mb6AOxoNGAxYDCMGcWP5C1GBf15bfGNO4VL678+Qybjl5E8g9lKQH2yGuBCvuIEb2Zug19/8GKjviGE+WKR3P7Ko0SjqsJPvvk8sYqHjrxdYmkLXu8=ci4ew756EmPAqg9FbVqB9S0vVIydcTUPZ0s69f7Iox9IB4Z6VOgJfCVg0kBRtYcy
  N3_KEY: c694314e-e9ee-413e-b999-9dcd3caf6d0d
services:
  - mysql
events:
  build:
    steps:
      -
        composer:
          type: script
          script:
            - 'composer install -vvv &'
            - 'secs=$((10*60)); while [ $secs -gt 0 ]; do    echo -e "$secs";    sleep 1;    : $((secs--)); done'            
            - 'mysql -u root -proot -e "CREATE DATABASE drupal"'
            - 'cd docroot'
            - '/usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ../vendor/bin/drush site-install -y --db-url=mysql://root:root@127.0.0.1:3306/drupal'
            - 'php -S 127.0.0.1:8081 &'
            - 'sleep 2'
            - 'cd ..'
            - ./vendor/bin/behat
      -
        deploy:
          script:
            - 'cd environments'
            - 'composer install'
            - 'php cloud-ode.php'
